version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  web1:
    image: ruby:latest
    command: tail -f /dev/null

  web2:
    image: "nginx"
    ports:
      - "8000:80"
